services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
    ports:
      - 8086:8086
    env_file:
      - ./influxdb/influx.env
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf:/etc/telegraf
    depends_on:
      - mosquitto
      - influxdb
    links:
      - mosquitto
      - influxdb
    ports:
      - '8125:8125'
    env_file:
      - ./influxdb/influx.env
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
volumes:
  shelly: